language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  nosetests -svd --with-doctest --with-coverage --cover-package=insar --where=insar

after_success: coveralls


